spring.application.name=productsservice
server.port=8080
aws.region=eu-west-3

# Picks up this from stack env vars: "AWS_PRODUCTSDDB_NAME"
aws.productsddb.name=products
amazon.dynamodb.endpoint=http://localhost:8000/
amazon.aws.accesskey=key
amazon.aws.secretkey=key2


# AWS_SNS_TOPIC_PRODUCT_EVENTS
aws.sns.topic.product.events=product-events

api.stage=test

asw.sns.notification.email=rupert.waldron@yahoo.co.uk

spring.threads.virtual.enabled=true

logging.level.com.amazonaws.xray=ERROR
logging.level.com.root=INFO
